spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: mapper/*.xml
  type-aliases-package: com.scxh.pagehelper.entity
pagehelper:
  helperDialect: mysql
  reasonable: true  #\u5F00\u542F\u4F18\u5316\uFF0C\u5982\u679C\u5F00\u542F\u4F18\u5316\uFF0C\u5728\u5206\u9875\u9875\u7801\u7ED3\u679C\u6CA1\u6709\u6570\u636E\u7684\u65F6\u5019,\u4F1A\u663E\u793A\u6709\u6570\u636E\u7684\u9875\u7801\u6570\u636E
  supportMethodsArguments: false #\u662F\u5426\u652F\u6301\u63A5\u53E3\u53C2\u6570\u6765\u4F20\u9012\u5206\u9875\u53C2\u6570\uFF0C\u9ED8\u8BA4false
  pageSizeZero: true #pageSize=0 \u8FD4\u56DE\u6240\u6709
  params: count=countSql
